### ISSUE TITLE
Spine preview

### ISSUE THREAD

**Issue by MilkTeaMO** [lastbattle/Harepacker-resurrected#105]
Sorry I can't speak English, so I used Google translate.

As shown below, in spine preview, the color display is flipped.
Since I don't know if it’s a bug or a problem with my own operation, I’ll submit a bug report here first.

And I want to ask, can the animation in Spine preview be exported?

![5NAIPBJM3AL`L4YQEYJPP37](https://user-images.githubusercontent.com/78784240/107326018-17dc3400-6aee-11eb-986d-977658c48f70.png)

![00`ORRP 2}DDJLJ5`5IM(@Y](https://user-images.githubusercontent.com/78784240/107326237-6c7faf00-6aee-11eb-8fb2-4c0f30e7c959.png)

**Comment by lastbattle** [comment]
What is the path of the following spine images with the image flipped? I'll take a look.

Yes, at present you cant export spine images as a png, jpeg or gif yet.

**Comment by MilkTeaMO** [comment]
The spine previews opened through .atlas are all flipped...
Currently I only viewed a part of UI.wz and Effect.wz

UI.wz/Login.img/RaceSelect_new/Back0/...
Effect.wz/Direction20.img/...

And thank you very much for your reply!

**Comment by lastbattle** [comment]
Fixed! Looks like it is decoding the image bytes to texture incorrectly.
I'll make a commit after some further testing.

![image](https://user-images.githubusercontent.com/4586194/108075637-8cdadb00-70a5-11eb-93f3-73e5363a76ca.png)

**Comment by lastbattle** [comment]
Feel free to pull it off the 'staging' branch, I shall mark this as resolved. 

https://github.com/lastbattle/Harepacker-resurrected/commit/95a8f17dcaee6cfe0fee0e88f92fd86490ef8fab

**Comment by lastbattle** [comment]
Update: I'll look into exporting it.

**Comment by MilkTeaMO** [comment]
XD Thank you very much, I am looking forward to the export

**Comment by lastbattle** [comment]
I think you might have to get a spine-runtime license in order to do that. It is supported right out of the box via the official editor.
![image](https://user-images.githubusercontent.com/4586194/108218723-e8719b00-716f-11eb-942b-7bd80ee023e5.png)
MapleStory currently uses spine v2.1.25 ~ v2.1.28 (2016).

There could be a work-around by extending the spine-csharp library myself, but I'll have to take a look at the license first. 

http://en.esotericsoftware.com/spine-export
